---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    region: us-east-1    
  tasks:
    - debug: var=vars
    - name: launch instance
      ec2:
        region: "{{ region }}"  
        key_name: EC2NVirginia  
        instance_type: t2.micro  
        image: ami-6057e21a  
        wait: yes    
        group: sg_webserver_useastone
      register: ec2  
    - name: associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item }}"
      with_items: "{{ ec2.instance_ids }}"
