---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
   region: us-east-1
   allowed_ip: 116.74.234.117/32
  tasks:
    - name: create database security group
      ec2_group:
        region: "{{ region }}"
        name: sg_database_useastone
        description: security group for apsydney database host
        rules:
          # allow ssh access from your ip address
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ allowed_ip }}"
          # allow mysql access from webserver group
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_name: sg_webserver_useastone
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0