---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Your Region
    region: us-east-1
  tasks:
    - name: Find EC2 Facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "instance-state-name": running
      register: instance_list
    
    - set_fact:
        instance_ids: "{{instance_list.instances|map(attribute='id')|list}}" 
    
    - ec2:
       region: "{{ region }}" 
       instance_ids: "{{instance_ids}}" 
       state: absent